version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8082:8000"
    env_file: .env
    depends_on:
      - postgresql
    networks:
      - jiranet

  jira:
    depends_on:
      - postgresql
    image: teamatldocker/jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8083:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=jira'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  postgresql:
    image: postgres:15.0-alpine3.16
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jira'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - 5050:80
    networks:
      - jiranet
    restart: unless-stopped
  
  sonarqube:
    image: library/sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      # - "conf:/opt/sonarqube/conf"
      - "extensions:/opt/sonarqube/extensions"
      - "logs_sonar:/opt/sonarqube/logs"
      - "data_sonar:/opt/sonarqube/data"
    depends_on:
      - postgresql
    networks:
      - jiranet
    environment:
      - sonar.jdbc.username=jira
      - sonar.jdbc.password=jira
      - sonar.jdbc.url=jdbc:postgresql://postgresql/sonarqube


volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
  pgadmin:
  extensions:
  logs_sonar:
  data_sonar:
  

networks:
  jiranet:
    driver: bridge