# Generated by Django 4.1.2 on 2022-10-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('CodeQuality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='core.codequality')),
            ],
        ),
    ]
